import { AIProject } from "./types";

export interface GeneratedFile {
    path: string;
    content: string;
    encoding?: 'utf-8' | 'base64';
}

export function generateCode(project: AIProject): GeneratedFile[] {
    const slug = project.title.toLowerCase().replace(/[^a-z0-9]/g, '-');
    const safeTitle = project.title.replace(/"/g, '\\"');
    const safeDesc = project.description.replace(/"/g, '\\"');

    const files: GeneratedFile[] = [
        {
            path: 'package.json',
            content: JSON.stringify({
                name: slug,
                version: '0.1.0',
                private: true,
                scripts: {
                    dev: 'next dev',
                    build: 'next build',
                    start: 'next start',
                    lint: 'next lint'
                },
                dependencies: {
                    'react': '^18',
                    'react-dom': '^18',
                    'next': '14.1.0',
                    'lucide-react': '^0.330.0',
                    'framer-motion': '^11.0.3',
                    'clsx': '^2.1.0',
                    'tailwind-merge': '^2.2.1'
                },
                devDependencies: {
                    '@types/node': '^20',
                    '@types/react': '^18',
                    '@types/react-dom': '^18',
                    'autoprefixer': '^10.0.1',
                    'postcss': '^8',
                    'tailwindcss': '^3.3.0',
                    'typescript': '^5'
                }
            }, null, 2)
        },
        {
            path: 'next.config.js',
            content: `/** @type {import('next').NextConfig} */
const nextConfig = {};
module.exports = nextConfig;`
        },
        {
            path: 'tsconfig.json',
            content: JSON.stringify({
                compilerOptions: {
                    lib: ["dom", "dom.iterable", "esnext"],
                    allowJs: true,
                    skipLibCheck: true,
                    strict: true,
                    noEmit: true,
                    esModuleInterop: true,
                    module: "esnext",
                    moduleResolution: "bundler",
                    resolveJsonModule: true,
                    isolatedModules: true,
                    jsx: "preserve",
                    incremental: true,
                    plugins: [{ name: "next" }],
                    paths: { "@/*": ["./*"] }
                },
                include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
                exclude: ["node_modules"]
            }, null, 2)
        },
        {
            path: 'app/layout.tsx',
            content: `import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "${safeTitle}",
  description: "${safeDesc}",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}`
        },
        {
            path: 'app/page.tsx',
            content: `import { ArrowRight, CheckCircle2, Code2, Cpu, Globe } from 'lucide-react';

export default function Home() {
  return (
    <main className="min-h-screen bg-black text-white selection:bg-blue-500/30">
        {/* Simple Header */}
        <header className="fixed top-0 w-full z-50 bg-black/50 backdrop-blur-xl border-b border-white/10">
            <div className="container mx-auto px-6 h-16 flex items-center justify-between">
                <span className="font-bold text-xl tracking-tight">${safeTitle}</span>
                <a href="#features" className="text-sm text-white/60 hover:text-white transition-colors">Features</a>
            </div>
        </header>

        {/* Hero */}
        <div className="relative pt-32 pb-20 px-6">
            <div className="absolute inset-0 bg-blue-500/10 blur-[100px] pointer-events-none" />
            <div className="container mx-auto max-w-4xl text-center relative z-10">
                <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/5 border border-white/10 mb-8">
                    <span className="w-2 h-2 rounded-full bg-green-400 animate-pulse" />
                    <span className="text-sm font-medium text-white/80">Generated by Gravity</span>
                </div>
                <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-8 bg-gradient-to-br from-white to-white/40 bg-clip-text text-transparent">
                    ${safeTitle}
                </h1>
                <p className="text-xl text-white/60 leading-relaxed mb-10 max-w-2xl mx-auto">
                    ${safeDesc}
                </p>
                <div className="flex items-center justify-center gap-4">
                    <button className="h-12 px-8 rounded-full bg-blue-600 hover:bg-blue-500 font-semibold flex items-center gap-2 transition-all">
                        Get Started <ArrowRight className="w-4 h-4" />
                    </button>
                    <button className="h-12 px-8 rounded-full bg-white/10 hover:bg-white/20 font-semibold transition-all">
                        Learn More
                    </button>
                </div>
            </div>
        </div>

        {/* Features Grid */}
        <div className="container mx-auto px-6 py-20" id="features">
            <div className="grid md:grid-cols-3 gap-6">
                <div className="p-8 rounded-3xl bg-white/5 border border-white/10 hover:border-white/20 transition-colors group">
                    <div className="w-12 h-12 rounded-2xl bg-blue-500/20 flex items-center justify-center mb-6 text-blue-400 group-hover:scale-110 transition-transform">
                        <Cpu className="w-6 h-6" />
                    </div>
                    <h3 className="text-xl font-bold mb-3">AI Powered</h3>
                    <p className="text-white/50">Built with advanced artificial intelligence at its core.</p>
                </div>
                <div className="p-8 rounded-3xl bg-white/5 border border-white/10 hover:border-white/20 transition-colors group">
                    <div className="w-12 h-12 rounded-2xl bg-purple-500/20 flex items-center justify-center mb-6 text-purple-400 group-hover:scale-110 transition-transform">
                        <Code2 className="w-6 h-6" />
                    </div>
                    <h3 className="text-xl font-bold mb-3">Modern Stack</h3>
                    <p className="text-white/50">Next.js 14, Tailwind CSS, and Typescript ready.</p>
                </div>
                <div className="p-8 rounded-3xl bg-white/5 border border-white/10 hover:border-white/20 transition-colors group">
                    <div className="w-12 h-12 rounded-2xl bg-green-500/20 flex items-center justify-center mb-6 text-green-400 group-hover:scale-110 transition-transform">
                        <Globe className="w-6 h-6" />
                    </div>
                    <h3 className="text-xl font-bold mb-3">Global Scale</h3>
                    <p className="text-white/50">Deployed to the edge for maximum performance.</p>
                </div>
            </div>
        </div>

        {/* Implementation Steps */}
        <div className="container mx-auto px-6 py-20 border-t border-white/5">
            <h2 className="text-3xl font-bold mb-10 text-center">Implementation Roadmap</h2>
            <div className="max-w-2xl mx-auto space-y-4">
                ${project.implementation_plan?.map(step => `
                <div className="flex items-start gap-4 p-4 rounded-2xl bg-white/5">
                    <CheckCircle2 className="w-5 h-5 text-blue-500 shrink-0 mt-1" />
                    <p className="text-white/80">${step.replace(/"/g, '&quot;')}</p>
                </div>`).join('') || ''}
            </div>
        </div>
    </main>
  );
}`
        },
        {
            path: 'app/globals.css',
            content: `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 255, 255, 255;
  --background-start-rgb: 0, 0, 0;
  --background-end-rgb: 0, 0, 0;
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}`
        },
        {
            path: '.gitignore',
            content: `node_modules
.next
.env
.env.local`
        }
    ];

    return files;
}
