"use client";

import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { motion } from 'framer-motion';
import { ArrowLeft, ArrowRight, Code2, Cpu, Globe, Rocket, Terminal, Box, Layers, Zap } from 'lucide-react';
import Link from 'next/link';
import { AIProject } from '@/lib/types';

// Theme Definitions
const THEMES = {
    midnight: {
        id: 'midnight',
        name: 'Midnight Modern',
        bg: 'bg-black',
        text: 'text-white',
        accent: 'blue',
        accentBg: 'bg-blue-600',
        accentText: 'text-blue-400',
        cardBg: 'bg-white/5',
        cardBorder: 'border-white/10',
        navBg: 'bg-black/50',
        gradient: 'from-blue-500/20 via-purple-500/5 to-transparent'
    },
    solar: {
        id: 'solar',
        name: 'Solar Light',
        bg: 'bg-white',
        text: 'text-slate-900',
        accent: 'orange',
        accentBg: 'bg-orange-500',
        accentText: 'text-orange-600',
        cardBg: 'bg-slate-50',
        cardBorder: 'border-slate-200',
        navBg: 'bg-white/80',
        gradient: 'from-orange-500/10 via-yellow-500/5 to-transparent'
    },
    cyber: {
        id: 'cyber',
        name: 'Cyber Neon',
        bg: 'bg-slate-900',
        text: 'text-white',
        accent: 'pink',
        accentBg: 'bg-pink-600',
        accentText: 'text-pink-400',
        cardBg: 'bg-slate-800/50',
        cardBorder: 'border-cyan-500/30',
        navBg: 'bg-slate-900/80',
        gradient: 'from-pink-600/20 via-cyan-500/10 to-transparent'
    },
    swiss: {
        id: 'swiss',
        name: 'Swiss Minimal',
        bg: 'bg-stone-100',
        text: 'text-black',
        accent: 'red',
        accentBg: 'bg-red-600',
        accentText: 'text-red-600',
        cardBg: 'bg-white',
        cardBorder: 'border-black',
        navBg: 'bg-stone-100/90',
        gradient: 'from-transparent to-transparent'
    }
};

// Deterministic Theme Selection
function getTheme(title: string) {
    if (!title) return THEMES.midnight;

    // Keyword matching overrides
    const lower = title.toLowerCase();
    if (lower.includes('game') || lower.includes('meta') || lower.includes('crypto')) return THEMES.cyber;
    if (lower.includes('dashboard') || lower.includes('saas') || lower.includes('crm')) return THEMES.solar;
    if (lower.includes('news') || lower.includes('blog') || lower.includes('portfolio')) return THEMES.swiss;

    // Fallback deterministic hash
    const sum = title.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    const themes = Object.values(THEMES);
    return themes[sum % themes.length];
}

export default function PreviewPage() {
    const pathname = usePathname();
    const [project, setProject] = useState<AIProject | null>(null);

    useEffect(() => {
        const stored = sessionStorage.getItem('previewProject');
        if (stored) {
            setProject(JSON.parse(stored));
        }
    }, []);

    const slug = pathname?.split('/').pop() || "Project";
    const title = project?.title || slug.split('-').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ');
    const description = project?.description || "A revolutionary application generated by Gravity.";

    // Select theme
    const theme = getTheme(title);

    return (
        <div className={`min-h-screen ${theme.bg} ${theme.text} font-sans selection:${theme.accentBg}/30 transition-colors duration-500`}>
            {/* Navigation Overlay */}
            <nav className={`fixed top-0 w-full z-50 ${theme.navBg} backdrop-blur-xl border-b ${theme.cardBorder}`}>
                <div className="container mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="flex items-center gap-4">
                        <Link href="/" className={`p-2 hover:${theme.text}/10 rounded-full transition-colors`} title="Back to Generator">
                            <ArrowLeft className="w-5 h-5" />
                        </Link>
                        <span className="font-bold text-xl tracking-tight">{title}</span>
                    </div>
                    <div className="flex items-center gap-3">
                        <div className={`hidden md:flex items-center gap-2 px-3 py-1 rounded-full border ${theme.cardBorder} bg-opacity-10 ${theme.cardBg}`}>
                            <span className={`w-2 h-2 rounded-full ${theme.accentBg} animate-pulse`} />
                            <span className={`text-xs font-medium opacity-80`}>Live Preview</span>
                        </div>
                        <a href="#features" className={`text-sm opacity-60 hover:opacity-100 transition-colors`}>Features</a>
                    </div>
                </div>
            </nav>

            <main>
                {/* Hero */}
                <div className="relative pt-32 pb-20 px-6 overflow-hidden">
                    <div className={`absolute inset-0 bg-gradient-to-br ${theme.gradient} opacity-50 pointer-events-none`} />
                    <motion.div
                        initial={{ opacity: 0, y: 30 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ duration: 0.8 }}
                        className="container mx-auto max-w-4xl text-center relative z-10"
                    >
                        <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-full border ${theme.cardBorder} mb-8 ${theme.cardBg}`}>
                            <Rocket className={`w-4 h-4 ${theme.accentText}`} />
                            <span className="text-sm font-medium opacity-80">v1.0 Release</span>
                        </div>
                        <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-8">
                            {title}
                        </h1>
                        <p className="text-xl opacity-60 leading-relaxed mb-10 max-w-2xl mx-auto">
                            {description}
                        </p>
                        <div className="flex items-center justify-center gap-4">
                            <button className={`h-12 px-8 rounded-full ${theme.accentBg} text-white font-semibold flex items-center gap-2 transition-all hover:scale-105 active:scale-95 shadow-lg shadow-${theme.accent}-500/25`}>
                                Get Started <ArrowRight className="w-4 h-4" />
                            </button>
                            <button className={`h-12 px-8 rounded-full border ${theme.cardBorder} ${theme.cardBg} hover:opacity-80 font-semibold transition-all hover:scale-105 active:scale-95`}>
                                Documentation
                            </button>
                        </div>
                    </motion.div>
                </div>

                {/* Features Grid */}
                <div className="container mx-auto px-6 py-20" id="features">
                    <div className="grid md:grid-cols-3 gap-6">
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.1 }}
                            className={`p-8 rounded-3xl ${theme.cardBg} border ${theme.cardBorder} hover:border-opacity-100 transition-all group`}
                        >
                            <div className={`w-12 h-12 rounded-2xl ${theme.accentBg} bg-opacity-10 flex items-center justify-center mb-6 ${theme.accentText} group-hover:scale-110 transition-transform`}>
                                <Cpu className="w-6 h-6" />
                            </div>
                            <h3 className="text-xl font-bold mb-3">AI Powered</h3>
                            <p className="opacity-50">Leveraging advanced algorithms to deliver intelligent solutions.</p>
                        </motion.div>
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.2 }}
                            className={`p-8 rounded-3xl ${theme.cardBg} border ${theme.cardBorder} hover:border-opacity-100 transition-all group`}
                        >
                            <div className={`w-12 h-12 rounded-2xl ${theme.accentBg} bg-opacity-10 flex items-center justify-center mb-6 ${theme.accentText} group-hover:scale-110 transition-transform`}>
                                <Code2 className="w-6 h-6" />
                            </div>
                            <h3 className="text-xl font-bold mb-3">Modern Stack</h3>
                            <div className="flex flex-wrap gap-2 mt-2">
                                {project?.tech_stack ? (
                                    project.tech_stack.slice(0, 4).map(t => (
                                        <span key={t} className={`text-xs px-2 py-1 rounded-md border ${theme.cardBorder} bg-opacity-20 opacity-70`}>{t}</span>
                                    ))
                                ) : (
                                    <p className="opacity-50">Next.js 14, Tailwind CSS, and Typescript ready.</p>
                                )}
                            </div>
                        </motion.div>
                        <motion.div
                            initial={{ opacity: 0, y: 20 }}
                            whileInView={{ opacity: 1, y: 0 }}
                            viewport={{ once: true }}
                            transition={{ delay: 0.3 }}
                            className={`p-8 rounded-3xl ${theme.cardBg} border ${theme.cardBorder} hover:border-opacity-100 transition-all group`}
                        >
                            <div className={`w-12 h-12 rounded-2xl ${theme.accentBg} bg-opacity-10 flex items-center justify-center mb-6 ${theme.accentText} group-hover:scale-110 transition-transform`}>
                                <Globe className="w-6 h-6" />
                            </div>
                            <h3 className="text-xl font-bold mb-3">Global Scale</h3>
                            <p className="opacity-50">Deployed to the edge for maximum performance and availability.</p>
                        </motion.div>
                    </div>
                </div>

                {/* Implementation Steps */}
                <div className={`container mx-auto px-6 py-20 border-t ${theme.cardBorder}`}>
                    <h2 className="text-3xl font-bold mb-10 text-center flex items-center justify-center gap-3">
                        <Terminal className="w-8 h-8 opacity-50" />
                        System Architecture
                    </h2>
                    <div className="max-w-3xl mx-auto space-y-4">
                        {project?.implementation_plan?.map((step, i) => (
                            <motion.div
                                key={i}
                                initial={{ opacity: 0, x: -20 }}
                                whileInView={{ opacity: 1, x: 0 }}
                                viewport={{ once: true }}
                                transition={{ delay: i * 0.1 }}
                                className={`flex items-start gap-4 p-4 rounded-2xl ${theme.cardBg} border ${theme.cardBorder}`}
                            >
                                <div className={`mt-1 w-6 h-6 rounded-full ${theme.accentBg} bg-opacity-10 flex items-center justify-center shrink-0 border border-opacity-20 ${theme.cardBorder}`}>
                                    <span className={`text-xs font-bold ${theme.accentText}`}>{i + 1}</span>
                                </div>
                                <p className="opacity-80 leading-relaxed">{step}</p>
                            </motion.div>
                        )) || (
                                <div className="text-center opacity-40 italic">Initialize project to view roadmap...</div>
                            )}
                    </div>
                </div>

                {/* Footer */}
                <footer className={`border-t ${theme.cardBorder} py-12 ${theme.bg} opacity-90`}>
                    <div className="container mx-auto px-6 text-center opacity-40">
                        <p>&copy; {new Date().getFullYear()} {title}. All rights reserved.</p>
                        <p className="text-xs mt-2">Powered by Gravity Engine • Theme: {theme.name}</p>
                    </div>
                </footer>
            </main>
        </div>
    );
}
